""" Settings file for Thunderpigs Rougelike Game """

"""
This is a really early alpha version of my roguelike. The main intend to create this game was to increase my pyrat skills while
having some fun.

If you have any comments feel free to give feedback on my github page

"""

""" General Game Settings """
title = "ThunderpigsRL"
creator = "Thunderpig"
language = "EN"
url = "https://github.com/Thunder-Pig/ThunderRL"

save_file = "tpsav.sav"

""" Screen Settings """
screen_width = 80
screen_height = 50

tile_file = "./images/dejavu16x16_gs_tc.png"
menu_background_file = "./images/menu_background.png"

""" Dungeon Creation """
map_width = 80
map_height = 43

room_max_size = 10
room_min_size = 6
max_rooms = 15

""" Main Menu """
if language == "DE":
	str_new_game = "[N] Neues Spiel"
	str_setup_game = "[S] Spielfigur konfigurieren"
	str_load_game = "[C] Spiel fortsetzen"
	str_quit_game = "[Q] Spiel beenden"
	str_file_not_found = "Spielstand nicht gefunden!"
	str_file_saved = "Spielstand gespeichert"
	welcome_text = "Hallo Abenteurer, willkommen zur " + title + " Dungeon Erfahrung!"
else:
	str_new_game = "[N] New Game"
	str_setup_game = "[S] Setup Player"
	str_load_game = "[C] Continue Game"
	str_quit_game = "[Q] Quit Game"
	str_file_not_found = "No saved game found."
	str_file_saved = "Game saved"
	welcome_text = "Hello Adventurerer, welcome to the " + title + " dungeon experience!"

""" Setup Game """
if language == "DE":
	str_setup_race = "Rasse auswaehlen"
	str_setup_class = "Klasse auswaehlen"
	str_barbarian = "Barbar"
	str_paladin = "Paladin"
	str_fighter = "Kaempfer"
	str_druid = "Druide"
	str_cleric = "Kleriker"
	str_monk = "Moench"
	str_ranger = "Waldlaeufer"
	str_bard = "Barde"
	str_rouge = "Schurke"
	str_sourcerer = "Hexenmeister"
	str_wizard = "Magier"
	str_human = "Mensch"
	str_elv = "Elb"
	str_dwarf = "Zwerg"
	str_gnome = "Gnom"
	str_halfling = "Halbling"
	str_halfelv = "Halb-Elb"
	str_halforc = "Halb-Ork"
else:
	str_setup_race = "Select Race"
	str_setup_class = "Select Class"
	str_barbarian = "Barbarian"
	str_paladin = "Paladin"
	str_fighter = "Fighter"
	str_druid = "Druid"
	str_cleric = "Cleric"
	str_monk = "Monk"
	str_ranger = "Ranger"
	str_bard = "Bard"
	str_rouge = "Rouge"
	str_sourcerer = "Sourcerer"
	str_wizard = "Wizard"
	str_human = "Human"
	str_elv = "Elv"
	str_dwarf = "Dwarf"
	str_gnome = "Gnome"
	str_halfling = "Halfling"
	str_halfelv = "Half Elv"
	str_halforc = "Half Orc"

""" Input Handlers """
if language == "DE":
	str_character_info = "Spielerinformationen"
	str_player_level = "Spielerstufe"
	str_xp_cur_level = "XP akt. Stufe"
	str_xp_total = "Gesamterfahrung"
	str_xp_next_level = "XP fuer naechste Stufe"
	str_invalid_entry = "Falsche Eingabe"
	str_message_history = "Nachrichtenverlauf"
	str_no_shop = "Hier gibt es keinen Laden"
	str_shop = "Laden"
	str_help = "Hilfe"
	str_level = "Stufe aufgestiegen"
	str_level_1 = "Gratulation, du bist eine Stufe aufgestiegen."
	str_level_2 = "Waehle ein Attribut zum Verbessern aus:"
	str_hp_increase = "Deine Trefferpunkte erhoehen sich."
	str_from = "aus"
	str_empty = "Leer"
	str_select_to_use = "Gegenstand zum Verwenden auswaehlen"
	str_select_to_drop = "Gegenstand zum Ablegen auswaehlen"
	str_select_to_inspect = "Gegenstand zum Untersuchen auswaehlen"
	str_pickup = "Du nimmst"
	str_inventory_full = "Dein Inventar ist voll"
	str_nothing_to_pickup = "Hier ist nichts zum aufheben"
	str_decicion = "Was moechtest du machen?"
	str_do_nothing = "Nichts machen."
	str_destroy = "Zerstoeren"
	str_lockpick_action = "Knacken"
	str_initiative = "Initiative"
	str_success = "Gewonnen!"
	str_skills = "Fertigkeiten"
	str_weight = "Gewicht"
	str_inspect_handler = "Untersuche Gegenstand"
	str_no_description = "Keine Informationen vorhanden."
	str_blocks_movement = "Blockiert Bewegung"
	str_needs_pickup = "Du musst {} vor Benutzung aufheben."
	str_content = "Inhalt"
	str_help_help = "[h] Hilfe"
	str_help_pickup = "[g] Aufheben"
	str_help_inventory = "[i] Inventory"
	str_help_character = "[o] Charakter"
	str_help_drop = "[d] Fallenlassen"
	str_help_look = "[l] Schauen"
	str_help_history = "[v] Historie"
	str_help_stairs = "[:] Treppe benutzen"
	str_help_shop = "[b] Einkaufen"
	str_help_search = "[m] Suchen"
	str_help_ranged = "[k] Fernangriff"
	str_help_inspect = "[j] Untersuchen"
else:
	str_character_info = "Character Information"
	str_player_level = "Player Level"
	str_xp_cur_level = "XP current Level"
	str_xp_total = "Total XP"
	str_xp_next_level = "XP for next Level"
	str_invalid_entry = "Invalid Entry"
	str_message_history = "Message History"
	str_no_shop = "There is no shop"
	str_shop = "Shop"
	str_help = "Help"
	str_level = "Level up"
	str_level_1 = "Congratulations, you level up."
	str_level_2 = "Choose an attribute to improve:"
	str_hp_increase = "Your HP increase."
	str_from = "from"
	str_empty = "Empty"
	str_select_to_use = "Select an item to use"
	str_select_to_drop = "Select an item to drop"
	str_select_to_inspect = "Select an item to inspect"
	str_pickup = "You pickup the"
	str_inventory_full = "Your inventory is full"
	str_nothing_to_pickup = "There is nothing to pickup"
	str_decicion = "What would you like to do?"
	str_do_nothing = "Do nothing."
	str_destroy = "Destroy"
	str_lockpick_action = "Lockpick"
	str_initiative = "Initiative"
	str_success = "Won!"
	str_skills = "Skills"
	str_weight = "Weight"
	str_inspect_handler = "Inspect item"
	str_no_description = "No details to show."
	str_blocks_movement = "Blocks movement"
	str_needs_pickup = "You need to pickup {} before use."
	str_content = "Content"
	str_help_help = "[h] Help"
	str_help_pickup = "[g] Pickup"
	str_help_inventory = "[i] Inventory"
	str_help_character = "[o] Character"
	str_help_drop = "[d] Drop"
	str_help_look = "[l] Look"
	str_help_history = "[v] History"
	str_help_stairs = "[:] Use stairs"
	str_help_shop = "[b] Shop"
	str_help_search = "[m] Search"
	str_help_ranged = "[k] Ranged Attack"
	str_help_inspect = "[j] Inspect object"
	
""" Entity Factories """
if language == "DE":
	str_dire = "Schreckliche"
	str_minor = "Schwache"
	str_money = "Muenzen"
	str_player_name = "Spieler"
	str_player_race = "Mensch"
	str_dog_name = "Hund"
	str_rat_name = "Ratte"
	str_orc_name = "Ork"
	str_troll_name = "Troll"
	str_dragon_name = "Drache"
	str_ant_name = "Ameise"
	str_sm_zombie_name = "Kleiner Zombie"
	str_lockpick_scroll = "Oeffnungsrune"
	str_lockpick_scroll_enc = ""
	str_amputation_scroll = "Amputationsrune"
	str_amputation_scroll_enc = ""
	str_blind_scroll = "Blindenrune"
	str_blind_scroll_enc = ""
	str_vision_scroll = "Visionsrune"
	str_vision_scroll_enc = ""
	str_dumb_scroll = "Stumme Rune"
	str_dumb_scroll_enc = ""
	str_fireball_scroll_name = "Feuerball Rune"
	str_fireball_scroll_name_enc = ""
	str_confusion_scroll_name = "Verwirrungsrune"
	str_confusion_scroll_name_enc = ""
	str_lightning_scroll_name = "Blitzrune"
	str_lightning_scroll_name_enc = ""
	str_health_potion_name = "Heiltrank"
	str_wodden_bow_name = "Holzbogen"
	str_arrow = "Pfeil"
	str_club_name = "Keule"
	str_dagger_name = "Dolch"
	str_spear_name = "Speer"
	str_axe_name = "Axt"
	str_short_sword_name = "Kurzschwert"
	str_leather_armor_name = "Lederruestung"
	str_scale_armor_name = "Plattenpanzer"
	str_chain_mail_name = "Kettenhemd"
	str_sm_wo_shield_name = "Kleines Holzschild"
	str_la_wo_shield_name = "Grosses Holzschild"
	str_tower_shield_name = "Turmschild"
	str_leather_hat_name = "Lederhut"
	str_leather_boots_name = "Lederstiefel"
	str_wo_chest_name = "Holzkiste"
	str_lockpick = "Dietriche"
	str_master = "Meister-"
	str_shopowner = "Verkaeufer"
	str_sheep = "Schaf"
else:
	str_dire = "Dire"
	str_minor = "Minor"
	str_money = "Coins"
	str_player_name = "Player"
	str_player_race = "Human"
	str_dog_name = "Dog"
	str_rat_name = "Rat"
	str_orc_name = "Orc"
	str_troll_name = "Troll"
	str_dragon_name = "Dragon"
	str_ant_name = "Ant"
	str_sm_zombie_name = "Small Zombie"
	str_lockpick_scroll = "Lockpick Scroll"
	str_amputation_scroll = "Amputation Scroll"
	str_blind_scroll = "Blinded Scroll"
	str_vision_scroll = "Vision Scroll"
	str_dumb_scroll = "Dumb Scroll"
	str_dumb_scroll_enc = ""
	str_fireball_scroll_name = "Fireball Scroll"
	str_confusion_scroll_name = "Confusion Scroll"
	str_lightning_scroll_name = "Lightning Scroll"
	str_health_potion_name = "Healing Potion"
	str_wodden_bow_name = "Wodden Bow"
	str_arrow = "Arrow"
	str_club_name = "Club"
	str_dagger_name = "Dagger"
	str_spear_name = "Spear"
	str_axe_name = "Axe"
	str_short_sword_name = "Short Sword"
	str_leather_armor_name = "Leather Armor"
	str_scale_armor_name = "Scale Armor"
	str_chain_mail_name = "Chain Mail"
	str_sm_wo_shield_name = "Small Wooden Shield"
	str_la_wo_shield_name = "Large Wooden Shield"
	str_tower_shield_name = "Tower Shield"
	str_leather_boots_name = "Leather Boots"
	str_leather_hat_name = "Leather Hat"
	str_wo_chest_name = "Wodden chest"
	str_lockpick = "Lockpick Set"
	str_master = "Master "
	str_shopowner = "Shop owner"
	str_sheep = "Sheep"
	
""" actions """

if language == "DE":
	str_no_target = "Kein Ziel."
	str_attack = "{} greift {} an"
	str_hits_target = " und erzielt {} Trefferpunkte."
	str_critical_hit = "Kritischer Treffer!"
	str_no_damage = " aber erzielt keinen Schaden."
	str_obj_destroyed = " und zerstoert es."
	str_not_walking = "Du kannst nicht laufen!"
	str_blocked = "Dieser Weg ist blockiert."
	str_blocked_by_something = "Dieser Weg ist durch etwas blockiert."
	str_no_door = "Hier ist keine Tuer."
	str_no_door_passage = "Du kannst keine Tueren passieren."
	str_no_ranged_weapon = "Du traegst keine Fernwaffe."
	str_no_weapon = "Du traegst keine Waffe."
	str_no_arrows = "Dir fehlen Pfeile oder Bolzen."
	str_no_arrows_left = "Dein Koecher ist leer."
	str_back_to_light = "Du moechtest den Dungeon nicht verlassen und die Sonne wiedersehen."
	str_no_stairs = "Hier sind keine Stufen oder eine Leiter."
	str_downstairs = "Du bist tiefer in den Dungeon geklettert."
	str_upstairs = "Du bist eine Ebene nach oben geklettert."
	str_no_lockpick_set = "Du hast kein Werkzeug um Schloesser zu oeffnen."
	str_lockpick_success = "Du hast das Schloss geknackt!"
	str_lockpick_fail = "Das Schloss bleibt leider zu."
	str_no_destroy = "{} kann nicht zerstoert werden."
	str_shake = "Es klappert in {}"
	str_something_breake = "Es ist etwas in {} zu Bruch gegangen."
	str_broken = " (zerbrochen)"
	str_place_item = "Du legst {} in {}."
	str_take_money = "Du nimmst {} {} aus {}."
	str_found = "Du findest {}."
	str_is_dumb ="scheint verstummt zu sein."
	str_is_friendly = "{} ist freundlich gesinnt."
	str_to_heavy = "Du kommst schlecht vorran weil du so schwer bist."
	str_unable_to_move = "Du kannst dich nicht bewegen."
	str_cant_be_destroyed = "{} kann nicht zerstoert werden."
	str_melee_needed = "Du benoetigst eine Nahkampfwaffe."
	str_weapon_type = "Du benoetigst eine Waffe mit {}."
else:
	str_no_target = "Nothing to attack."
	str_attack = "{} attacks {}"
	str_hits_target = " and deals {} HP damage."
	str_critical_hit = "Critical Hit!"
	str_no_damage = " but does no damage."
	str_obj_destroyed = " and destroys it."
	str_not_walking = "You can't walk!"
	str_blocked = "This way is blocked."
	str_blocked_by_something = "This way is blocked by something."
	str_no_door = "Here is no door."
	str_no_door_passage = "You are not allowed to pass doors."
	str_no_ranged_weapon = "You dont have a ranged weapon equipped."
	str_no_weapon = "You have no weapon equipped."
	str_no_arrows = "You dont have arrows or bolts."
	str_no_arrows_left = "Your quiver is empty."
	str_back_to_light = "You won't leave the dungeon and go back to light."
	str_no_stairs = "Here are no stairs or a ladder."
	str_downstairs = "You climbed deeper into the dungeon."
	str_upstairs = "You climbed one dungeon level upwards."
	str_no_lockpick_set = "You don't have a lockpick set."
	str_lockpick_success = "You successfully picked the lock!"
	str_lockpick_fail = "The lock stays closed."
	str_no_destroy = "{} can't be destroyed."
	str_shake = "Something shakes in {}."
	str_something_breake = "Something broke in {}."
	str_broken = " (broken)"
	str_place_item = "You place {} in {}."
	str_take_money = "You took {} {} out of {}."
	str_found = "You found {}."
	str_is_dumb ="seems to be dumb."
	str_is_friendly = "{} is friendly."
	str_to_heavy = "You have problems to move because you are to heavy."
	str_unable_to_move = "You are unable to move."
	str_cant_be_destroyed = "{} can't be destroyed."
	str_melee_needed = "You need a melee weapon."
	str_weapon_type = "You need a weapon with {}."

""" Equipment Class """
if language == "DE":
	str_equip = "Du traegst jetzt "
	str_unequip = "Abgelegt ist "
else:
	str_equip = "You equip the "
	str_unequip = "You unequip the "

""" Fighter Class """

if language == "DE":
	str_died = "Du bist eines qualvollen Todes gestorben!"
	str_killed = " wurde durch dich getoetet!"
	str_remains = "Leiche von "
	str_attack_dialog = "Angreifen"
	str_swap_place = "Platz tauschen"
else:
	str_died = "You died a terrible dead!"
	str_killed = " was killed by you!"
	str_remains = "Remains of "
	str_attack_dialog = "Attack"
	str_swap_place = "Swap places"

""" Skills """
if language == "DE":
	str_fov_change = "Sicht veraendert"
	str_vision_reduced = "Deine Sicht hat sich verschlechtert."
	str_vision_improved = "Deine Sicht hat sich verbessert."
	str_npc_vision_reduced = "{} wurde geblended und kann nichts sehen!"
	str_npc_vision_improved = "Die Sicht von {} scheint sich verbessert zu haben."
	str_cant_be_cast = "{} kann nicht auf {} angewandt werden."
else:
	str_fov_change = "FoV changed"
	str_vision_reduced = "Your vision is reduced."
	str_vision_improved = "Your vision is improved."
	str_npc_vision_reduced = "{} was blinded and can't see."
	str_npc_vision_improved = "{} vision seems to be improved."
	str_cant_be_cast = "{} cant be cast on {}."

""" consumable """
if language == "DE":
	str_select_target = "Ziel auswaehlen."
	str_target_not_visible = "Du kannst kein Ziel ausserhalb deines Sichtbereichs auswaehlen!"
	str_must_select_target = "Du musst ein Gegner als Ziel auswaehlen!"
	str_cant_confuse_yourself = "Du kannst dich nicht selbst verwirren."
	str_target_confused = " ist verwirrt und seine Augen sehen sonderbar aus."
	str_hp_recovered = " Trefferpunkte wiederhergestellt durch "
	str_health_full = "Deine Lebenspunkte sind bereits auf Maximum."
	str_explosion = " Lebenspunkte wurden durch eine gewaltige Explosion abgezogen von "
	str_no_target_in_radius = "Nichts zu treffen im Zielbereich."
	str_no_target_close_enough = "Kein Ziel in der Naehe."
	str_lightning = " Lebenspunkte wurden durch einen Blitzschlag abgezogen von "
	str_close_door = "Du schliesst die Tuer."
	str_searching = "Untersuche Umgebung..."
	str_found_door = "Versteckte Tuer gefunden!"
	str_no_lock = "{} hat kein Schloss."
	str_not_locked = "{} ist nicht verschlossen."
	str_use_broken = "Du verletzt dich an {}."
	str_amputate = "{} wurde {} amputiert."
	str_no_organ = "Kein Koerperteil zum amputieren."
	str_no_amputate = "Nichts zu amputieren."
	str_dumb = "Du bist stumm."
else:
	str_select_target = "Select a target."
	str_target_not_visible = "You cannot target an area that you cannot see."
	str_must_select_target = "You must select an enemy to target."
	str_cant_confuse_yourself = "You cant confuse yourself."
	str_target_confused = " looks confused and his eyes starts to stumble around."
	str_hp_recovered = " HP recovered by "
	str_health_full = "Your health is already at maximum."
	str_explosion = " HP damage were taken by an exposion to "
	str_no_target_in_radius = "No target in area."
	str_no_target_close_enough = "No target close enough."
	str_lightning = " HP damage were taken by an lightning strike to "
	str_close_door = "You close the door."
	str_searching = "Searching..."
	str_found_door = "Found hidden door!"
	str_no_lock = "{} has no lock."
	str_not_locked = "{} is not locked."
	str_use_broken = "You get hurt by {}."
	str_amputate = "{} got {} amputated."
	str_no_organ = "No body part to amputate."
	str_no_amputate = "Nothing to amputate."
	str_dumb = "You are dumb."

""" Furniture """
if language == "DE":
	str_tree = "Baum"
	str_fountain = "Brunnen"
	str_pillar = "Saeule"
	str_cloud = "Wolke"
	str_ironbar = "Gitterstaebe"
	str_door = "Tuer"
	str_trap = "Falle"
	str_button = "Knopf"
	str_button_finish = "Du drueckst den Knopf und alles boese verschwindet aus der Welt. Geh heim und trink ein Bier!"
else:
	str_tree = "Tree"
	str_fountain = "Fountain"
	str_pillar = "Pillar"
	str_cloud = "Cloud"
	str_ironbar = "Ironbars"
	str_door = "Door"
	str_trap = "Trap"
	str_button = "Button"
	str_button_finish = "You press the button and everything evil is gone from this world. Go home and get a beer!"



""" Usable (Furniture) """
if language == "DE":
	str_run_into = "{} ist fast in {} reingerannt."
	str_kick_tree = "Tritt gegen den Baum."
	str_kick_tree_perform = "Du trittst ordentlich gegen den Baum..."
	str_hit_by_branch = "...und dir faellt ein Ast direkt auf den Kopf. Du erleidest {} HP Schaden."
	str_get_potion = "...und ein Heiltrank faellt dir direkt in deine Haende."
	str_only_noise = "...und es macht nur 'dong', sonst nichts."
	str_tree_collapse = "...und der Baum faellt um."
	str_tree_damage = "...und der Baum faellt auf dich. Daber erleidest du {} HP Schaden."
	str_amputate_foot = "...dabei bleibt dein Fuss stecken. Beim herausziehen reisst er ab und du erleidest {} HP Schaden."
	str_full_healing = "Du trinkst aus dem Brunnen den besten Heilsaft den du je probiert hast."
	str_healing = "Du trinkst aus dem Brunnen klares, frisches Wasser."
	str_dirty = "Du trinkst aus dem Brunnen aber das Wasser war schmutzig"
	str_quaff = "Du trinkst aus dem Brunnen aber nichts passiert."
	str_fountain_dry = "Der Brunnen ist ausgetrocknet."
	str_pre_dry = "Ausgetrockneter "
	str_cloud_step = "Du trittst in die Wolken, deine Sicht ist eingeschraenkt."
	str_door_broken = "Diese Tuer ist zerstoert."
	str_pick_lock = "Knacke Schloss"
	str_break = "Aufbrechen"
	str_open_door = "Oeffne Tuer"
	str_uncharged = "Du hast Glueck das {} nicht aktiviert ist."
	str_trap_damage = "Du erleidest durch {} {} HP Schaden ({})."
	str_rock_drop = "Ein {} faellt von der Decke!"
	str_teleported = "Du wurdest teleportiert!"
	str_foot_cutoff = "Dein Fuss wurde durch {} abgeschnitten!"
	str_drops_next = "Ein {} faellt zu Boden."

else:
	str_run_into = "{} almost run into {}."
	str_kick_tree = "Kick the tree."
	str_kick_tree_perform = "You're kicking the tree in anger..."
	str_hit_by_branch = "...and a branch is hitting your head and causes {} HP damage."
	str_get_potion = "...and a healing potion drops directly into your hands."
	str_only_noise = "...and it just makes 'clonk', nothing more."
	str_tree_collapse = "...and the tree collapses."
	str_tree_damage = "...and the tree falls directly into you, causing {} HP damage."
	str_amputate_foot = "...thereby your foot gets stuck. When you try to free your foot, it tears off, causing {} HP damage."
	str_full_healing = "You quaff from the fountain and taste the best healing juice you ever had."
	str_healing = "You quaff from the fountain cold and clear water."
	str_dirty = "You quaff from the fountain but the water was dirty."
	str_quaff = "You quaff from the fountain but nothing happens."
	str_fountain_dry = "The fountain is dry."
	str_pre_dry = "Dry "
	str_cloud_step = "You step into the clouds, you view is blocked."
	str_broken = "This door is destroyed."
	str_pick_lock = "Pick the lock"
	str_break = "Break it"
	str_open_door = "Open door"
	str_uncharged = "You are lucky that {} is not charged."
	str_trap_damage = "{} deals {} HP ({}) damage on you."
	str_rock_drop = "A {} drops from the ceiling."
	str_teleported = "You were teleported!"
	str_foot_cutoff = "Your foot was cut by {}."
	str_drops_next = "A {} drops down."
		
""" Level """
if language == "DE":
	str_gain_xp = "Du erhaelst {} Erfahrungspunkte."
	str_advance_level = "Du steigst auf Stufe {} auf."
	str_inc_strength = "Du fuehlst dich staerker!"
	str_inc_dexterity = "Du bist viel wendiger!"
	str_inc_condition = "Du kannst viel mehr aushalten!"
	str_inc_intelligence = "Du fuehlst dich klueger!"
	str_inc_wisdom = "Du hast die Weisheit mit Loeffeln gefressen!"
	str_inc_charisma = "Du bist so ein toller Typ!"
	str_skill_points = "Faehigkeitspunkte"
else:
	str_gain_xp = "You gain {} XP."
	str_advance_level = "You advance to level {}."
	str_inc_strength = "You feel much stronger!"
	str_inc_dexterity = "Your movements are getting swifter!"
	str_inc_condition = "You can last longer!"
	str_inc_intelligence = "Your getting much cleverer!"
	str_inc_wisdom = "You know the answer to everything!"
	str_inc_charisma = "You are so smart!"
	str_skill_points = "Skill points"

""" Attributes """
if language == "DE":
	str_strength = "Staerke"
	str_dexterity = "Beweglichkeit"
	str_constitution = "Konstitution"
	str_wisdom = "Weisheit"
	str_intelligence = "Intelligenz"
	str_charisma = "Charisma"
	str_armor_class = "Ruestungsklasse"
	str_race = "Rasse"
	str_class = "Klasse"
	str_size = "Groesse"
else:
	str_strength = "Strength"
	str_dexterity = "Dexterity"
	str_constitution = "Constitution"
	str_wisdom = "Wisdom"
	str_intelligence = "Intelligence"
	str_charisma = "Charisma"
	str_armor_class = "Armor Class"
	str_race = "Race"
	str_class = "Class"
	str_size = "Size"


""" Sizes """
if language == "DE":
	str_colossal = "Kollosal"
	str_gargantuan = "Gigantisch"
	str_huge = "Riesig"
	str_large = "Gross"
	str_medium = "Mittelgross"
	str_small = "Klein"
	str_tiny = "Sehr klein"
	str_diminutive = "Winzig"
	str_fine = "Mini"
else:
	str_colossal = "Colossal"
	str_gargantuan = "Gargantuan"
	str_huge = "Huge"
	str_large = "Large"
	str_medium = "Medium"
	str_small = "Small"
	str_tiny = "Tiny"
	str_diminutive = "Diminutive"
	str_fine = "Fine"

""" Materials """
if language == "DE":
	str_material = "Material"
	str_paper = "Papier"
	str_ice = "Eis"
	str_leather = "Leder"
	str_metal = "Metall"
	str_wood = "Holz"
	str_stone = "Stein"
	str_glas = "Glas"
	str_mithril = "Mithril"
	str_adamant = "Adamantit"
else:
	str_material = "Material"
	str_paper = "Paper"
	str_ice = "Ice"
	str_leather = "Leather"
	str_metal = "Metal"
	str_wood = "Wood"
	str_stone = "Stone"
	str_glas = "Glas"
	str_mithril = "Mithril"
	str_adamant = "Adamant"

""" Damage Types """
if language == "DE":
	str_piercing = "Stichschaden"
	str_slashing = "Schnittschaden"
	str_bludgeoning = "Schlagschaden"
	str_water_damage = "Wasserschaden"
	str_fire_damage = "Feuerschaden"
	str_explosion_damage = "Explosionsschaden"

else:
	str_piercing = "Piercing"
	str_slashing = "Slashing"
	str_bludgeoning = "Bludgeoning"
	str_water_damage = "Water"
	str_fire_damage = "Fire"
	str_explosion_damage = "Explosion"

""" Trap Types """
if language == "DE":
	str_trap_fire = "Feuer"								# inserted
	str_trap_water = "Wasser"							# inserted
	str_trap_dart = "Dart"								# inserted
	str_trap_arrow = "Pfeil"							# inserted
	str_trap_bolt = "Bolzen"							# inserted
	str_trap_anti_magic = "Anti-Magie"						# erst wenn Magie eingefuegt ist
	str_trap_bear = "Baeren"							# inserted
	str_trap_hole = "Loch"								# inserted
	str_trap_falling_rock = "Steinfall"					# inserted
	str_trap_land_mine = "Landmine"						# inserted
	str_trap_level_teleport = "Ebenenteleporter"
	str_trap_teleporter = "Teleporter"					# inserted (mit Bug in MovementAction)
	str_trap_magic = "Magie"								# erst wenn Magie eingefuegt ist
	str_trap_pit = "Fallgrube"								# Fallgrube mit Wasserschaden? Unklar wie genau
	str_trap_polymorph = "Polymorph"						# schwierig
	str_trap_rolling_boulder = "Rollender Stein"			# schwierig
	str_trap_rust = "Rost"									# bisher kein Rost eingefuegt
	str_trap_gas = "Gas"									# unklar wie genau einfuegen (nur WaitAction oder...)
	str_trap_spike = "Stachel"							# inserted
	str_trap_board = "Quitschendes Brett"					# Macht erst Sinn wenn Monster darauf reagieren koennen
	str_trap_hatch = "Falltuer"
	str_trap_vibrating = "Vibrator"							# unklar
	str_trap_web = "Netz"								# inserted
	str_trap_container = "Behaelter"						# schwierig, evtl. als gesonderter Behaelter einfuegen
	str_trap_door = "Tuer"									# schwierig, evtl. als gesonderte Tuer einfuegen
else:
	str_trap_fire = "Fire"
	str_trap_water = "Water"
	str_trap_dart = "Dart"
	str_trap_arrow = "Arrow"
	str_trap_bolt = "Bolt"
	str_trap_anti_magic = "Anti-Magic"
	str_trap_bear = "Beartrap"
	str_trap_hole = "Hole"
	str_trap_falling_rock = "Stone-fall"
	str_trap_land_mine = "Landmine"
	str_trap_level_teleport = "Level Teleporter"
	str_trap_teleporter = "Teleporter"
	str_trap_magic = "Magic"
	str_trap_pit = "Pit"
	str_trap_polymorph = "Polymorph"
	str_trap_rolling_boulder = "Rolling stone"
	str_trap_rust = "Rust"
	str_trap_gas = "Gas"
	str_trap_spike = "Spike"
	str_trap_board = "Squeeking bole"
	str_trap_hatch = "Hatch"
	str_trap_vibrating = "Vibrator"
	str_trap_web = "Net"
	str_trap_container = "Container"
	str_trap_door = "Door"	

""" Lock """
if language == "DE":
	str_trap_unlocked = "Du hast die {} deaktiviert."
	str_unlocked = "(deaktiviert)"
else:
	str_trap_unlocked = "You deactivated {}."
	str_unlocked = "(deactivated)"	
	
""" Render functions """
if language == "DE":
	str_dungeon_level = "Dung. Ebene"
	str_experience = "Erfahrung"
	str_weapon = "Waffe"
	str_quiver = "Koecher"
else:
	str_experience = "Experience"
	str_dungeon_level = "Dung. Level"
	str_weapon = "Weapon"
	str_quiver = "Quiver"

""" Inventory """
if language == "DE":
	str_drop_item = "Du legst {} ab."
else:
	str_drop_item = "You drop {}."

""" Banking """
if language == "DE":
	str_not_enough_money = "Du hast nicht genug Muenzen."
else:
	str_not_enough_money = "You don't have enough coins."

""" AI """
if language == "DE":
	str_no_longer_confused = "{} ist nicht mehr verwirrt."
else:
	str_no_longer_confused = "{} is no longer confused."

